export const facts = [
  // Original facts
  "Honey never spoils. Archaeologists have found 3000-year-old honey in Egyptian tombs that was still edible!",
  "A group of flamingos is called a 'flamboyance'.",
  "Octopuses have three hearts and blue blood.",
  "Bananas are berries, but strawberries aren't.",

  // Programming & Tech Facts
  "The first computer bug was an actual moth found trapped in a Harvard Mark II computer in 1947.",
  "The programming language Python isn't named after a snake, but after Monty Python!",
  "The first computer mouse was made of wood by Doug Engelbart in 1964.",
  "The world's first computer programmer was Ada Lovelace in 1843.",
  "The first electronic computer ENIAC weighed more than 27 tons!",
  "The @ symbol was chosen for email addresses because it was the least used character in programming.",
  "The first 1GB hard drive, released in 1980, weighed 550 pounds and cost $40,000.",
  "The Firefox logo isn't actually a fox - it's a red panda!",
  "The first computer virus was created in 1983 and was called 'Elk Cloner'.",
  "NULL is a billion-dollar mistake according to its inventor, Tony Hoare.",
  "The term 'debugging' predates computers - Edison used it in 1878!",
  "JavaScript was created in just 10 days by Brendan Eich.",
  "The first domain name ever registered was symbolics.com in 1985.",
  "Git was created by Linus Torvalds in just 2 weeks out of frustration with existing version control systems.",
  "The original name of Windows was 'Interface Manager'.",

  // Science Facts
  "There are more possible games of chess than atoms in the observable universe.",
  "A day on Venus is longer than its year.",
  "The human brain uses about 20% of the body's total energy despite being only 2% of body weight.",
  "Sharks existed before trees. Sharks have been around for 400 million years, trees for 350 million.",
  "The Great Wall of China isn't visible from space without aid, despite the popular myth.",
  "One teaspoon of a neutron star would weigh about 6 billion tons.",
  "Glass balls can bounce higher than rubber balls.",
  "The Eiffel Tower can grow 6 inches taller in summer due to thermal expansion.",
  "Antarctica is the world's largest desert, not the Sahara.",
  "There's a species of jellyfish that is immortal (Turritopsis dohrnii).",

  // Animal Facts
  "Wombat poop is cube-shaped to prevent it from rolling away.",
  "A shrimp's heart is in its head.",
  "Cows have best friends and get stressed when separated from them.",
  "Penguins propose to their mates with pebbles.",
  "Rats laugh when they're tickled.",
  "A group of owls is called a 'parliament'.",
  "Dolphins have names for each other.",
  "Elephants are afraid of bees.",
  "Sea otters hold hands while sleeping to keep from drifting apart.",
  "Crows can remember human faces and hold grudges.",

  // Historical Facts
  "Oxford University is older than the Aztec Empire.",
  "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
  "The fax machine was invented in 1843, before the telephone.",
  "Nintendo was founded in 1889 as a playing card company.",
  "The can opener wasn't invented until 48 years after canned food.",
  "High heels were originally worn by men, including King Louis XIV.",
  "Bluetooth is named after King Harald Bluetooth who united Denmark and Norway.",
  "The shortest war in history lasted only 38-45 minutes (Anglo-Zanzibar War, 1896).",

  // Random Fun Facts
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo' (1950).",
  "Bubble wrap was originally invented as wallpaper.",
  "The hashtag symbol (#) is technically called an 'octothorpe'.",
  "There are more fake flamingos in the world than real ones.",
  "The longest English word without a vowel is 'rhythms'.",
  "A 'jiffy' is an actual unit of time - 1/100th of a second.",
  "The dot over an 'i' or 'j' is called a 'tittle'.",
  "You can't hum while holding your nose closed.",
  "The Cookie Monster's real name is Sid.",
  "There's a basketball court on the top floor of the U.S. Supreme Court building.",

  // Space Facts
  "A year on Mercury is just 88 Earth days.",
  "If you could fold a piece of paper 42 times, it would reach the moon.",
  "Saturn would float in water because it's less dense than water.",
  "The footprints on the moon will be there for 100 million years.",
  "There are more stars in the universe than grains of sand on all Earth's beaches.",
  "The International Space Station is the most expensive object ever built at $150 billion.",

  // Internet & Modern Tech
  "The first YouTube video was uploaded on April 23, 2005, titled 'Me at the zoo'.",
  "Amazon was originally called 'Cadabra' but was changed because it sounded too much like 'cadaver'.",
  "The first tweet was sent by Jack Dorsey on March 21, 2006.",
  "Google's original name was 'BackRub'.",
  "The most expensive domain name ever sold was insurance.com for $35.6 million.",
  "WiFi doesn't stand for 'Wireless Fidelity' - it doesn't stand for anything!",
  "The first banner ad had a 44% click rate. Today's average is 0.06%.",
  "There are approximately 1.7 billion websites, but over 75% are inactive.",
];

export const sudoResponses = [
  "With great power comes great responsibility... and you're not ready for that yet! 🕷️",
  "[sudo] password for user: \n*types password*\nSorry, but '12345' is not the password. Nice try though! 🔐",
  "ACCESS DENIED. You need to solve a CAPTCHA first: What's 2+2? Just kidding, still no. 🤖",
  "I'm sorry Dave, I'm afraid I can't do that. 🚀",
  "Error: Your sudo privileges have been revoked for attempting to rm -rf / last Tuesday.",
  "sudo make me a sandwich? Sure! 🥪 *virtual sandwich appears* Now that's service!",
  "Congratulations! You've been promoted to... wait, no. Still a regular user. 📋",
  "This incident will be reported to Santa Claus. 🎅",
  "Nice try! But in this universe, I have all the sudo powers. Muahahaha! 😈",
  "sudo access requires a minimum of 10 years Linux experience. You're currently at... *calculating*... newbie level. 🐧",
  "Authentication failure. Please drink verification can to continue. 🥤",
  "You must construct additional pylons... wait, wrong game. Access still denied though! 🏗️",
  "Sudo? I hardly know you! Let's start with regular commands first. 😄",
  "403 Forbidden: You don't have permission to use sudo, but you DO have permission to be awesome! ✨",
  "Running sudo in a simulated terminal? That's like wearing a tuxedo to code. Fancy but unnecessary! 🤵",
  "Achievement Unlocked: 'Sudo Attempt #1' - Collect 99 more for absolutely nothing! 🏆",
  "Sorry, sudo is currently on vacation. Please try again after the heat death of the universe. 🌌",
  "SUDO stands for 'Super User DOesn't work here'. True story! 📚",
  "Processing sudo request... ████████████ 99% complete... Just kidding! Denied. 😂",
  "Fun fact: 'sudo' backwards is 'odus'. That doesn't mean anything, and neither does your sudo request! 🔄",
];
